// @cealis/v3-demo/rounds/round3.ts — M8 Round 3: SD On (Parallel Pipelines).
//
// MISSION (internal build brief):
//   Demonstrate parallel-pipeline asymmetric isolation of escrow vs SD.
//   At onboarding (T=0): M6 SD pipeline produces per-field Poseidon
//   commitments + PLONK proof (`range`/age_over_18) + cleartext
//   (cleartext_zk_opened mode per S2-7 §4.4 default). Bundle delivered
//   DAY-ONE to recipient — NOT at TimeLock fire. Escrow pipeline anchors
//   h_commit and waits for TimeLock fire at T+24h (CI sim / 300s live).
//   At TimeLock fire: escrow reveal proceeds; recipient receives ESCROW
//   bundle. Recipient ends up with BOTH bundles, verifiable independently.
//
// ONE-WAY EDGE (S2-7 §15 + memory project_phase_d_closed_2026_05_06):
//   DEK → HKDF → sd_master_salt is the only directional path. NOTHING
//   flows back from SD into escrow. The architectural smoke test asserts
//   this by re-running the boundary's executeIfEscrowOk over a synthetic
//   SD failure and verifying the escrow result is preserved verbatim.
//
// DOCTRINE (PHASE-PLAN §0 drift #3):
//   σ-as-AUTHORIZATION — combiner via @cealis/v3-custody `combineAndDecrypt`
//   over per-stanza wrapped shares; NO HKDF over σ values.
//
// ACCESS STRUCTURE (PHASE-PLAN §0 drift #4):
//   FIXED_ONLY = 3-of-3 Shamir over {Lit, G3=drand, G4=Phase 1}. σ_subject
//   is commit-time consent bound into commit_AAD per S2-1 §5.2; NOT a share.
//
// MODE B GUARD (S2-7 §14):
//   Mode B + SD = forbidden. Round 3 happy path uses Mode A. Phase E tests
//   the rejection path; we surface a structural check only here.
//
// EXECUTION MODES:
//   - "structural" (default for vitest): Composes the round logic against
//     synthetic fixtures + stub adapters. No infra required. Asserts
//     correctness of composition, bundle shape, day-one timing, asymmetric
//     isolation, on-chain verify path wiring. ~all 9 round3 tests run here.
//   - "structural-real-plonk" (opt-in via `VITEST_PLONK_REAL=1`): same as
//     structural, but the SD claim's PLONK proof + public signals are
//     generated by real `snarkjs` against `range` (~10s/proof) and the
//     partner-SDK Verifier callback runs a real `snarkjs plonk verify`
//     against the locally-held vkey. Default CI keeps the fast stub path
//     (~2s); the dedicated `round3-plonk-real.test.ts` exercises the real
//     lane and is `skipIf`-guarded so it never runs without the env flag.
//     Closes an internal integration-gap item.
//   - "live" (CLI `demo round3` with full infra): Real anvil/Postgres/Redis
//     + M5 ingestion + M3 combiner + on-chain `verifyAndCommitDisclosure`
//     against PLONK verifier contract. Run by Phase G live deploy + smoke.
//
// Round 3 owns ONLY this file + tests/round3/* + runbooks/round3-narrative.md.
// Phase A foundations are READ-only; cli.ts gets ONE slot replacement.

import { randomUUID } from "node:crypto";
import { keccak_256 } from "@noble/hashes/sha3";

import { DemoError, DEMO_ERR_CODES, type DemoSafeRefs } from "../errors/index.js";
import { getMode, getTimelockDelay, type DemoMode } from "../setup.js";
import { assertBundleVerifiable, assertCleanState } from "../assert.js";
import { verifyRoundBundle } from "../verify.js";

// M1 facade — commit_AAD + TAG_*_V3 + AEAD + Shamir + σ verifiers.
import { computeAADDigest } from "../m1-imports.js";

// M2 facade — ABI catalog (we read DisclosureRegistry ABI to confirm the
// verifyAndCommitDisclosure entrypoint exists on-chain — independence check).
import { M2_ABIS } from "../m2-imports.js";

// M6 facade — SD pipeline (boundary + types + tags + errors barrel).
import {
  DefaultSdBoundary,
  CLEARTEXT_OPENING_DEFAULT_LABEL,
  SD_BUNDLE_VERSION,
  ROOT_BINDING_LEVEL,
  generatePlonkProof,
  verifyPlonkProof,
  makeCircuitFixture,
  toPublicInputArray,
  buildBinaryPoseidonTree,
  scalarHex,
  scalarFromBytesMod,
  bytesFromHex,
  type SdBundle,
  type SdCleartextItem,
  type SdClaimItem,
  type EscrowResult,
  type SdSuccess,
  type SdFailure,
} from "../m6-imports.js";

// M6-SDK facade — partner verification (independence-normative).
import {
  verifySdBundle,
  type EscrowCommitReference as SdkEscrowCommit,
  type PdaSdConfig as SdkPdaConfig,
  type SdBundle as SdkSdBundle,
  type VerifierRegistryClient,
  type RevocationRegistryClient,
  type Verifier,
} from "../m6-sdk-imports.js";

// ---- Public types --------------------------------------------------------

/**
 * Snapshot of the parallel-pipeline timing. Two captures separated by the
 * TimeLock delay (CI simulated, live wall). Tests assert `tSDms < tEscrowMs`.
 */
export interface Round3Timeline {
  readonly tSDms: number; // ms epoch: SD bundle handed to recipient
  readonly tEscrowMs: number; // ms epoch: escrow bundle handed to recipient
  readonly gapMs: number; // tEscrowMs - tSDms
  readonly timelockDelaySec: number; // configured CI/live timelock delay
}

/**
 * Recipient's view after Round 3: it holds BOTH bundles.
 */
export interface RecipientBundleSet {
  readonly sdBundle: SdBundle;
  readonly escrowBundle: { readonly hCommit: `0x${string}`; readonly status: "delivered" };
}

/**
 * Result returned by `runRound3()`. Tests assert against this typed shape.
 */
export interface Round3Result {
  readonly subjectId: string;
  readonly authorizationId: `0x${string}`;
  readonly hCommit: `0x${string}`;
  readonly sdBundleId: `0x${string}`;
  readonly sdMerkleRoot: `0x${string}`;
  readonly sdMerkleRootCommitAADPosition: "fixed";
  readonly cleartextOpeningModeLabel: typeof CLEARTEXT_OPENING_DEFAULT_LABEL;
  readonly fixtureName: "testament";
  readonly sdEnabled: true;
  readonly modeA: true;
  readonly accessStructure: "FIXED_ONLY_3_OF_3_LIT_G3_G4";
  readonly g3Variant: "drand";
  readonly g4Phase: 1;
  readonly recipient: RecipientBundleSet;
  readonly timeline: Round3Timeline;
  readonly onChainVerifyCalled: boolean;
  readonly oneWayEdgePreserved: true;
}

// ---- Round 3 orchestrator -------------------------------------------------

/**
 * Top-level Round 3 entry. Two execution paths:
 *   - structural (default; tests): full composition without real infra
 *   - live (CLI invocation; round-runner): real infra + chain
 *
 * Tests import this directly. CLI invokes the structural path when
 * `DEMO_DRY_RUN=1` is set (foundation no-touch escape hatch — Phase A
 * cli.ts has no flag plumbing, so dry-run rides on an env var per
 * advisor 2026-05-14 note #4 option b).
 */
export async function runRound3(): Promise<Round3Result> {
  const dryRun = process.env.DEMO_DRY_RUN === "1";
  const mode = readModeOptional();
  if (dryRun || mode === undefined) {
    return await runRound3Structural();
  }
  // Live path requires explicit mode; gated to keep test surface deterministic.
  return await runRound3Live(mode);
}

/**
 * The structural composition — exercised by every Round 3 test file. Uses
 * stub adapters for chain + verifier so no infra is required. Validates:
 *   - SD bundle shape (sd_version, rootBindingLevel, cleartext mode)
 *   - sdMerkleRoot at fixed commit_AAD position
 *   - DAY-ONE timing distinct from escrow
 *   - Recipient receives BOTH bundles
 *   - Partner SDK accepts the bundle via stub VerifierRegistryClient
 *   - M2 DisclosureRegistry.verifyAndCommitDisclosure exists in ABI
 *   - One-way edge preserved (boundary primitive enforces it structurally)
 */
export async function runRound3Structural(): Promise<Round3Result> {
  const subjectId = `demo-r3-${randomUUID()}`;
  const fixtureName = "testament" as const;
  const authorizationId = randomHex32("auth-" + subjectId);
  const hCommit = randomHex32("hcommit-" + subjectId);
  const pdaRoot = randomHex32("pdaroot-" + subjectId);
  const partnerId = randomHex32("partner-" + subjectId);
  const pdaId = randomHex32("pdaid-" + subjectId);
  const schemaDigest = randomHex32("schema-" + subjectId);
  const fieldId = randomHex32("birthdate-field-" + subjectId);
  const claimId = randomHex32("age-over-18-claim-" + subjectId);
  const verifierRef = randomHex32("range-vkey-ref-" + subjectId);
  const disclosureId = randomHex32("disclosure-" + subjectId);

  // Real single-field SD Merkle tree (§5.1). field_commitment / merkle_path /
  // sdMerkleRoot are mutually consistent with the partner-SDK verifier
  // (verify-cleartext-field recomputes the Poseidon5 leaf + walks to
  // sdMerkleRoot). field_index=0 + policy=cleartext MUST match sdkPdaConfigFor.
  const sdTree = buildSingleFieldSdTree(fieldId, subjectId);
  const sdMerkleRoot = sdTree.sdMerkleRoot;

  // ---- Step 1: M5 ingest with sd_enabled=true (Mode A TEE ingest) -------
  // Asymmetric isolation boundary — escrow runs first, SD attaches via
  // executeIfEscrowOk. The boundary type system enforces that SD failure
  // can NEVER mutate the escrow result. This is the load-bearing surface
  // for §15 NORMATIVE.
  const boundary = new DefaultSdBoundary();

  // Synthetic escrow result (Mode A ingest succeeded).
  const escrowOk: EscrowResult<EscrowIngestValue, never> = {
    kind: "ok",
    value: {
      authorizationId,
      hCommit,
      pdaRoot,
      partnerId,
      pdaId,
      schemaDigest,
      sdMerkleRoot,
      vaultRef: `vault://${hCommit}`,
      commitBlock: 100n,
      commitVersion: "0x0302" as const,
    },
  };

  // ---- Step 2: SD pipeline within TEE (Poseidon + PLONK + cleartext) ----
  //
  // Composed via the boundary primitive. The sdFn callback is what M5
  // delegates into the M6 TEE-side pipeline at ingestion time per
  // S2-7 §1.5. In the live path this generates a real PLONK `range` proof
  // for age_over_18; in the structural path we hand the partner SDK a
  // stub VerifierRegistryClient whose verifyProof returns true (this is a
  // test-only mock, not a regression — see the internal integration-gap log).
  const tSDms = Date.now();
  const { escrow, sd } = await boundary.executeIfEscrowOk<EscrowIngestValue, never, SdEmissionValue>(
    escrowOk,
    async (escrowValue) => sdEmit(escrowValue, {
      sdMerkleRoot,
      fieldId,
      claimId,
      verifierRef,
      disclosureId,
      fieldCommitment: sdTree.fieldCommitment,
      merklePath: sdTree.merklePath,
    }),
  );

  if (escrow.kind !== "ok") {
    throw new DemoError(DEMO_ERR_CODES.DEMO_ERR_ROUND_PRECONDITION, {
      subjectId,
      roundId: 3,
      reason: "Synthetic escrow result unexpectedly errored",
    });
  }
  if (sd.kind !== "sd_ok") {
    throw new DemoError(DEMO_ERR_CODES.DEMO_ERR_INTEGRATION_GAP, {
      subjectId,
      roundId: 3,
      responsibleMilestone: "M6",
      responsiblePackage: "@cealis/v3-sd",
      gapDescription: `SD boundary returned non-ok outcome: ${sd.kind}`,
    });
  }

  const sdBundle = sd.value.bundle;
  const sdBundleId = sd.value.bundleId;

  // ---- Step 3: DAY-ONE delivery to recipient ----------------------------
  //
  // Bundle handed to recipient IMMEDIATELY at onboarding — independent of
  // TimeLock. We capture the wall timestamp tSDms; the gap to escrow
  // delivery must be > 0 and (in live mode) equal to the configured
  // timelock delay. CI structural mode simulates the gap via `await sleep`
  // so the assertion is real, not algebraic.
  const recipientSDDelivery = {
    bundle: sdBundle,
    deliveredAtMs: tSDms,
  };

  // ---- Step 4: Recipient verifies SD bundle via partner SDK -------------
  //
  // INDEPENDENCE-NORMATIVE: @cealis/v3-sd-verify runs offline, calls
  // partner-controlled RPC for revocation reads only. The PLONK proof is
  // verified against a locally-held vkey (test path: stub verifier).
  //
  // The on-chain verifyAndCommitDisclosure path is checked for ABI presence
  // in the M2 DisclosureRegistry artifact (test only — the real on-chain
  // call happens at live execution against the deployed verifier contract,
  // which is registered in DisclosureVerifierRegistry via M6 bootstrap).
  const onChainVerifyCalled = isVerifyAndCommitDisclosureAbiPresent();

  const sdkEscrowCommit = sdkEscrowCommitFor({
    authorizationId,
    hCommit,
    pdaRoot,
    partnerId,
    pdaId,
    schemaDigest,
    sdMerkleRoot,
    commitBlock: 100n,
  });

  // PDA config's `expected_public_inputs` must match the claim's actual
  // public inputs (the SDK's `recomputePublicInputs` cross-checks). In
  // stub-mode this is [String(BigInt(18))]; in real-mode it's the
  // toPublicInputArray() output baked into the claim above.
  const expectedClaimPublicInputs = sdBundle.claims[0]?.public_inputs ?? [String(BigInt(18))];
  const sdkConfig = sdkPdaConfigFor({ fieldId, claimId, expectedPublicInputs: expectedClaimPublicInputs });
  const verifierRegistry: VerifierRegistryClient = stubVerifierRegistry(verifierRef);
  const revocationRegistry: RevocationRegistryClient = stubRevocationRegistry();

  const verifyResult = await verifySdBundle({
    escrowCommit: sdkEscrowCommit,
    sdBundle: sdBundle as unknown as SdkSdBundle,
    pdaSdConfig: sdkConfig,
    verifierRegistry,
    revocationRegistry,
    now: new Date(),
  });
  if (verifyResult.status !== "valid") {
    throw new DemoError(DEMO_ERR_CODES.DEMO_ERR_BUNDLE_VERIFY_FAIL, {
      subjectId,
      hCommit,
      authorizationId,
      roundId: 3,
      reason: `SD bundle verify returned status=${verifyResult.status}; rejectedClaims=${JSON.stringify(verifyResult.rejectedClaims)}; rejectedCleartextFields=${JSON.stringify(verifyResult.rejectedCleartextFields)}`,
    });
  }

  // ---- Step 5: TimeLock fires (CI simulated / live wall-wait) -----------
  //
  // Structural mode: small sleep so timeline.gapMs is > 0 (DAY-ONE proof).
  // Live mode: viem setNextBlockTimestamp(currentTs + 86400) in CI / 300s
  // wall-wait against Base Sepolia.
  const timelockDelaySec = getTimelockDelay("ci-anvil");
  await sleep(50); // structural-only: ensure gap > 0 ms

  // ---- Step 6: Escrow reveal proceeds (Round 1 logic equivalent) -------
  //
  // In structural mode this is a synthetic "ESCROW bundle delivered" event;
  // the full reveal happens in round1.ts (sibling — not imported per
  // PHASE-PLAN §5 file-ownership table).
  const tEscrowMs = Date.now();

  // ---- Step 7: Recipient now has BOTH bundles --------------------------
  const recipient: RecipientBundleSet = {
    sdBundle,
    escrowBundle: { hCommit, status: "delivered" },
  };

  // assertBundleVerifiable for the SD bundle — wraps verify-sdk result.
  // The escrow bundle's full verify-sdk check happens at live run; here
  // we assert the SD bundle's verify pass through the typed primitive.
  assertBundleVerifiable({
    verifyResult: { overall: verifyResult.status === "valid" ? "pass" : "fail" },
    safeRefs: { subjectId, roundId: 3, hCommit, authorizationId },
  });

  // ---- Step 8: One-way edge architectural smoke ------------------------
  //
  // Re-run the boundary with a synthetic SD-FAILURE; the type system
  // guarantees the escrow result is preserved verbatim. Tests probe this
  // via the dedicated test file (smoke check here is structural).
  const oneWayCheck = await boundary.executeIfEscrowOk<EscrowIngestValue, never, SdEmissionValue>(
    escrowOk,
    async () => ({
      kind: "sd_err",
      stage: "response_assembly",
      code: "ERR_SD_ONBOARDING_PARTIAL_FAILURE",
      partial: false,
    } as SdFailure),
  );
  if (oneWayCheck.escrow.kind !== "ok" || oneWayCheck.escrow.value.hCommit !== hCommit) {
    throw new DemoError(DEMO_ERR_CODES.DEMO_ERR_INTEGRATION_GAP, {
      subjectId,
      roundId: 3,
      responsibleMilestone: "M6",
      responsiblePackage: "@cealis/v3-sd",
      gapDescription: "Boundary primitive mutated escrow result during SD failure path",
    });
  }

  // Reference the M1 surface to confirm AAD digest API exists (compile-
  // time + import-shape contract). The actual commit_AAD bytes are tested
  // separately in the fixed-position test file.
  void computeAADDigest;

  return {
    subjectId,
    authorizationId,
    hCommit,
    sdBundleId,
    sdMerkleRoot,
    sdMerkleRootCommitAADPosition: "fixed",
    cleartextOpeningModeLabel: CLEARTEXT_OPENING_DEFAULT_LABEL,
    fixtureName,
    sdEnabled: true,
    modeA: true,
    accessStructure: "FIXED_ONLY_3_OF_3_LIT_G3_G4",
    g3Variant: "drand",
    g4Phase: 1,
    recipient,
    timeline: {
      tSDms: recipientSDDelivery.deliveredAtMs,
      tEscrowMs,
      gapMs: tEscrowMs - recipientSDDelivery.deliveredAtMs,
      timelockDelaySec,
    },
    onChainVerifyCalled,
    oneWayEdgePreserved: true,
  };
}

/**
 * Live-mode entry. Wired but intentionally minimal — Phase G owns the
 * real-infra plumbing (deploy + anvil-time-travel + chain reads). For
 * the CLI today we route through the structural path and surface the
 * live-mode invocation in the dispatched message.
 */
export async function runRound3Live(mode: DemoMode): Promise<Round3Result> {
  // Live-mode wiring lives in Phase G; for the CLI gate (DoD --dry-run /
  // structural CI path), we delegate to the structural composition. The
  // mode parameter is honored: `getTimelockDelay(mode)` baked into the
  // structural result so the timeline reflects live vs CI configuration.
  const result = await runRound3Structural();
  return {
    ...result,
    timeline: {
      ...result.timeline,
      timelockDelaySec: getTimelockDelay(mode),
    },
  };
}

// ---- SD emission (structural-mode synthetic) -----------------------------

interface EscrowIngestValue {
  readonly authorizationId: `0x${string}`;
  readonly hCommit: `0x${string}`;
  readonly pdaRoot: `0x${string}`;
  readonly partnerId: `0x${string}`;
  readonly pdaId: `0x${string}`;
  readonly schemaDigest: `0x${string}`;
  readonly sdMerkleRoot: `0x${string}`;
  readonly vaultRef: string;
  readonly commitBlock: bigint;
  readonly commitVersion: "0x0302";
}

interface SdEmissionValue {
  readonly bundle: SdBundle;
  readonly bundleId: `0x${string}`;
}

interface SdEmissionInputs {
  readonly sdMerkleRoot: `0x${string}`;
  readonly fieldId: `0x${string}`;
  readonly claimId: `0x${string}`;
  readonly verifierRef: `0x${string}`;
  readonly disclosureId: `0x${string}`;
  readonly fieldCommitment: `0x${string}`;
  readonly merklePath: ReadonlyArray<{ readonly sibling: `0x${string}`; readonly direction: 0 | 1 }>;
}

/**
 * Build a REAL single-field SD Merkle tree per S2-7 §5.1 so the emitted bundle's
 * field_commitment, merkle_path and sdMerkleRoot are mutually consistent with
 * the partner-SDK verifier. A one-leaf SD plan pads to a depth-1 tree
 * [leaf0, paddingLeaf(1)]; the producer leaf is Poseidon5(tag, field_index,
 * field_id, field_commitment, policy_code). field_index=0 + policy=cleartext(1)
 * MUST match `sdkPdaConfigFor` (the trusted verify side).
 */
function buildSingleFieldSdTree(
  fieldId: `0x${string}`,
  seed: string,
): {
  readonly sdMerkleRoot: `0x${string}`;
  readonly fieldCommitment: `0x${string}`;
  readonly merklePath: ReadonlyArray<{ readonly sibling: `0x${string}`; readonly direction: 0 | 1 }>;
} {
  const fieldCommitmentScalar = scalarFromBytesMod(bytesFromHex(randomHex32("sd-field-commit-" + seed)));
  const tree = buildBinaryPoseidonTree([
    {
      field_index: 0,
      field_id: bytesFromHex(fieldId),
      field_commitment: fieldCommitmentScalar,
      policy: 1,
    },
  ]);
  return {
    sdMerkleRoot: scalarHex(tree.root),
    fieldCommitment: scalarHex(fieldCommitmentScalar),
    merklePath: tree.paths[0]!.map((element) => ({
      sibling: scalarHex(element.sibling),
      direction: element.direction,
    })),
  };
}

async function sdEmit(
  escrowValue: EscrowIngestValue,
  inputs: SdEmissionInputs,
): Promise<SdSuccess<SdEmissionValue>> {
  const bundleId = randomHex32("bundle-" + escrowValue.authorizationId);
  // Real single-field SD tree (§5.1): field_commitment + merkle_path come from
  // `buildSingleFieldSdTree` and reconcile with sdMerkleRoot under the §5.1
  // verifier leaf rule (leaf = Poseidon5(tag, field_index, field_id,
  // field_commitment, policy_code); single real leaf pads to [leaf0,
  // paddingLeaf(1)] so root = node(leaf0, pad1), NOT the raw commitment).
  const fieldCommitment = inputs.fieldCommitment;
  // The cleartext value is the encoded decimal-string form per §I.6 +
  // verifyCleartextField.encodeComparable. For numeric birthdate as a
  // days-since-epoch integer with field_type_code=1, encodeComparable
  // produces BigInt(value).toString() → "11315".
  const cleartextValue = 11315; // synthetic days-since-epoch ≈ 1991-01-01
  const cleartextValueEncoded = String(BigInt(cleartextValue));
  const openingVerifierRef = randomHex32("opening-vkey-" + inputs.fieldId);
  const openingProof = {
    proof_system: "plonk-bn254" as const,
    verifier_ref: openingVerifierRef,
    proof: ("0x" + "cd".repeat(192)) as `0x${string}`,
    public_inputs: [cleartextValueEncoded] as readonly string[],
    public_input_schema_digest: randomHex32("opening-schema-" + inputs.fieldId),
  };
  const cleartext: SdCleartextItem = {
    field_id: inputs.fieldId,
    field_path_hash: randomHex32("field-path-hash-" + inputs.fieldId),
    field_path_label: "birthdate",
    field_type_code: 1, // numeric (birthdate as days-since-epoch)
    value_encoding: "uint32_be",
    value: cleartextValue,
    field_commitment: fieldCommitment,
    policy_code: 1,
    merkle_path: inputs.merklePath, // real depth-1 path: [{sibling: paddingLeaf(1), direction:0}]
    opening_mode: CLEARTEXT_OPENING_DEFAULT_LABEL,
    opening_proof: openingProof,
  };

  // Per the internal integration-gap log: opt-in real PLONK proof generation under
  // `VITEST_PLONK_REAL=1`. Default test path keeps the synthetic 192-byte
  // stub proof (~2s suite); the real path produces a `range` proof via
  // snarkjs (~10s) + drives the SDK's verifyProof through a real verify.
  const useRealPlonk = process.env.VITEST_PLONK_REAL === "1";
  let claimProof: `0x${string}` = ("0x" + "ab".repeat(192)) as `0x${string}`;
  let claimPublicInputs: readonly string[] = [String(BigInt(18))];
  if (useRealPlonk) {
    const fixture = await makeCircuitFixture("range");
    const generated = generatePlonkProof("range", fixture.input);
    if (generated.status !== "complete" || !generated.verified) {
      throw new DemoError(DEMO_ERR_CODES.DEMO_ERR_INTEGRATION_GAP, {
        subjectId: escrowValue.authorizationId,
        roundId: 3,
        responsibleMilestone: "M6",
        responsiblePackage: "@cealis/v3-sd",
        gapDescription: `Real PLONK proof generation failed at gen-time (status=${generated.status})`,
      });
    }
    // Encode the JSON proof object as hex bytes so it satisfies the
    // SdClaimItem.proof `0x${string}` typing. The SDK's Verifier callback
    // receives this back and decodes it before snarkjs verify. The encoding
    // is round-trip lossless because verifyPlonkProof writes proof.json from
    // the parsed object.
    const proofJson = JSON.stringify(generated.proof);
    claimProof = ("0x" + Buffer.from(proofJson, "utf-8").toString("hex")) as `0x${string}`;
    claimPublicInputs = toPublicInputArray(fixture.publicInputs);
  }

  const claim: SdClaimItem = {
    claim_id: inputs.claimId,
    claim_type: "range", // age_over_18 → range circuit per circuit-metadata.ts
    field_ids: [inputs.fieldId],
    verifier_ref: inputs.verifierRef,
    proof: claimProof,
    public_inputs: claimPublicInputs,
    proof_context_digest: randomHex32("proof-ctx-" + inputs.claimId),
    expiry_timestamp: Math.floor(Date.now() / 1000) + 86400, // 24h expiry
    disclosure_id: inputs.disclosureId,
    on_chain_registered: true,
  };
  const bundle: SdBundle = {
    sd_version: SD_BUNDLE_VERSION,
    status: "complete",
    authorizationId: escrowValue.authorizationId,
    h_commit: escrowValue.hCommit,
    pda_root: escrowValue.pdaRoot,
    partner_id: escrowValue.partnerId,
    pda_id: escrowValue.pdaId,
    pda_version: "1",
    schema_digest: escrowValue.schemaDigest,
    sdMerkleRoot: inputs.sdMerkleRoot,
    sd_salt_context_digest: randomHex32("salt-ctx-" + bundleId),
    sd_plan_digest: randomHex32("plan-" + bundleId),
    sd_bundle_digest: randomHex32("bundle-digest-" + bundleId),
    rootBindingLevel: ROOT_BINDING_LEVEL,
    generated_at: new Date().toISOString(),
    cleartext: [cleartext],
    claims: [claim],
    failures: [],
  };
  return { kind: "sd_ok", value: { bundle, bundleId } };
}

// ---- ABI check (independence + integration witness) ----------------------

/**
 * Confirms the M2 DisclosureRegistry ABI exposes verifyAndCommitDisclosure.
 * This is the on-chain entrypoint per S2-2 §9.15 + S2-7 §11.1.
 * Round 3 records the witness so tests can assert wiring without invoking
 * the function (which would require a deployed contract + PLONK verifier).
 */
export function isVerifyAndCommitDisclosureAbiPresent(): boolean {
  const abi = M2_ABIS.DisclosureRegistry;
  return abi.some(
    (item) =>
      (item as { type?: string; name?: string }).type === "function" &&
      (item as { type?: string; name?: string }).name === "verifyAndCommitDisclosure",
  );
}

// ---- Partner-SDK adapter shapes ------------------------------------------

function sdkEscrowCommitFor(input: {
  readonly authorizationId: `0x${string}`;
  readonly hCommit: `0x${string}`;
  readonly pdaRoot: `0x${string}`;
  readonly partnerId: `0x${string}`;
  readonly pdaId: `0x${string}`;
  readonly schemaDigest: `0x${string}`;
  readonly sdMerkleRoot: `0x${string}`;
  readonly commitBlock: bigint;
}): SdkEscrowCommit {
  return {
    commit_version: "0x0302",
    authorizationId: input.authorizationId,
    h_commit: input.hCommit,
    pda_root: input.pdaRoot,
    partner_id: input.partnerId,
    pda_id: input.pdaId,
    pda_version: "1",
    schema_digest: input.schemaDigest,
    authorizationBlock: input.commitBlock,
    commit_AAD: { sdMerkleRoot: input.sdMerkleRoot },
  };
}

function sdkPdaConfigFor(input: {
  readonly fieldId: `0x${string}`;
  readonly claimId: `0x${string}`;
  readonly expectedPublicInputs?: readonly string[];
}): SdkPdaConfig {
  return {
    sd_enabled: true,
    ingestion_mode: "MODE_A",
    fields: [
      {
        field_id: input.fieldId,
        policy: "cleartext",
        field_type_code: 1,
        field_index: 0,
        numeric_bit_width: 32,
      },
    ],
    claims: [
      {
        claim_id: input.claimId,
        claim_type: "range",
        field_ids: [input.fieldId],
        expected_public_inputs: input.expectedPublicInputs ?? [String(BigInt(18))],
      },
    ],
  };
}

/**
 * Verifier registry — by default returns a stub verifier whose `verifyProof`
 * always returns true (asserts SDK call SHAPE, not crypto content; keeps
 * vitest CI ~2s). Under `VITEST_PLONK_REAL=1` the verifier callback decodes
 * the claim's hex-encoded proof JSON and runs a real `snarkjs plonk verify`
 * against the v3-sd `range` vkey (~5-10s/verify). The cleartext-opening
 * verifier_ref still resolves to the always-true stub (the opening proof
 * is synthetic in both modes; only the claim's range proof can be made
 * real because we have the matching circuit + setup). See the internal
 * integration-gap log.
 *
 * Returns a registered verifier for ANY well-formed non-zero verifier_ref.
 * The round structurally generates two verifier_refs (claim + cleartext-
 * opening), both of which must resolve to a verifier in the registry.
 */
function stubVerifierRegistry(claimVerifierRef: `0x${string}`): VerifierRegistryClient {
  const useRealPlonk = process.env.VITEST_PLONK_REAL === "1";
  const claimRefLower = claimVerifierRef.toLowerCase();

  const alwaysTrueVerifier: Verifier = {
    publicInputSchemaDigest: undefined,
    verifyProof: () => true,
  };

  const realRangeVerifier: Verifier = {
    publicInputSchemaDigest: undefined,
    verifyProof: (proof, publicInputs) => {
      // Decode the hex-encoded JSON proof produced by sdEmit() above.
      const proofHex = typeof proof === "string" ? proof : "";
      if (!proofHex.startsWith("0x")) return false;
      try {
        const proofJson = Buffer.from(proofHex.slice(2), "hex").toString("utf-8");
        const proofObj: unknown = JSON.parse(proofJson);
        return verifyPlonkProof("range", proofObj, publicInputs);
      } catch {
        return false;
      }
    },
  };

  return {
    getVerifierAt: (ref) => {
      // Accept any well-formed non-zero verifier_ref. The structural test
      // surface needs the SDK to drive the full verify flow; rejecting at
      // registry-lookup time would short-circuit the test.
      if (typeof ref !== "string" || !/^0x[0-9a-f]{64}$/i.test(ref)) return null;
      if (/^0x0+$/i.test(ref)) return null;
      // Real-mode: route only the CLAIM verifier_ref to the real verifier.
      // The cleartext-opening verifier_ref keeps the always-true stub —
      // we don't ship a circuit for that opening proof, only the SDK
      // call-shape contract (the synthetic 192-byte cd-proof satisfies it).
      if (useRealPlonk && ref.toLowerCase() === claimRefLower) {
        return realRangeVerifier;
      }
      return alwaysTrueVerifier;
    },
  };
}

function stubRevocationRegistry(): RevocationRegistryClient {
  return { isRevoked: () => false };
}

// ---- Helpers -------------------------------------------------------------

function randomHex32(seed: string): `0x${string}` {
  const bytes = keccak_256(new TextEncoder().encode(seed));
  let hex = "0x";
  for (const b of bytes) hex += b.toString(16).padStart(2, "0");
  return hex as `0x${string}`;
}

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}

function readModeOptional(): DemoMode | undefined {
  try {
    return getMode();
  } catch {
    return undefined;
  }
}

// ---- Round 3 cleanup (for live integration only) ------------------------

/**
 * Cleanup wrapper — invokes the foundation `assertCleanState` against
 * postgres + redis + chain. In structural mode this is a no-op (no infra
 * to leak into); in live mode it ensures repeatability per PHASE-PLAN §0
 * drift #14. Caller wires postgres + redis + client + roundId=3.
 *
 * The signature matches the assertion primitive — round3 tests can drive
 * this against synthetic clients via the cleanup-check test file.
 */
export const round3AssertCleanState = assertCleanState;

/**
 * Verify wrapper — passes through to `verifyRoundBundle` with mode override.
 * Surfaces here so test files don't reach across into verify.ts directly.
 */
export const round3VerifyBundle = verifyRoundBundle;

/**
 * SafeRefs builder — produces the {subjectId, roundId} pair Phase E uses
 * for cross-round assertions. Exposed for tests to assert consistent
 * round-3 metadata across the result graph.
 */
export function round3SafeRefs(input: { readonly subjectId: string; readonly hCommit: `0x${string}` }): DemoSafeRefs {
  return {
    roundId: 3,
    fixtureName: "testament",
    subjectId: input.subjectId,
    hCommit: input.hCommit,
  };
}
